apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-cjcc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-cjcc
    app.kubernetes.io/part-of: ci1t-830-0039-app
  name: devfile-sample-cjcc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-cjcc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-cjcc
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0039-tenant/ci1t-830-0039-app/devfile-sample-cjcc@sha256:9ddd5b2ad46451b60d574e565e93d7a7f5bc71f39bddbc5f08a0321a01b34bed
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
